Repository Mohitjadaun2026/PMS-CGC-U, pull requests merged in 2025-09, with the labels that each got.

#142 Add Privacy Policy page and route
  frontend/src/App.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/PrivacyPolicy.jsx
Labels: level 1, gssoc25

#155 Fixed the contributing .md
  Contributing.md
Labels: level 1, gssoc25

#158 Add the comprehensive cookie policy page
  frontend/src/App.jsx
  frontend/src/components/CookiePolicy.jsx
  frontend/src/components/cookiePolicy.css
  frontend/src/index.css
Labels: gssoc25, Level 2

#163 fix(home): make 'Learn More' button navigate to About page (#161)
  frontend/src/components/home.jsx
Labels: level 1, gssoc25

#176 Unwanted Border Removed
  frontend/src/components/sign.css
Labels: level 1, gssoc25

#182 Feat/add loader and disable effect
  frontend/src/components/Sign.jsx
  frontend/src/components/sign.css
Labels: gssoc25, Level 2

#187 Added the GDPR Compliance page
  frontend/src/App.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/GdprCompliance.jsx
  frontend/src/components/gdprCompliance.css
  frontend/src/index.css
Labels: gssoc25, Level 3

#188 Added Terms of service page
  frontend/src/App.jsx
  frontend/src/components/TermsOfService.jsx
  frontend/src/components/termsOfService.css
Labels: gssoc25, Level 2

#199 About Page Styling Changed
  frontend/src/components/About.jsx
  frontend/src/components/about.css
Labels: gssoc25, Level 2

#207 updated job button
  frontend/src/components/jobs.css
Labels: level 1, gssoc25

#211 feat: Add dynamic progress bar to signup page
  frontend/src/components/Sign.jsx
  frontend/src/components/sign.css
Labels: gssoc25, Level 2

#210 Headings in home page updated
  frontend/src/components/home.css
Labels: level 1, gssoc25

#209 Extra padding removed
  frontend/src/components/home.css
Labels: level 1, gssoc25

#216 Refactor adminController.js for Better Error Handling and Code Consistency
  backend/controllers/adminContoller.js
Labels: gssoc25, Level 2
