Repository Mohitjadaun2026/PMS-CGC-U, pull requests merged in 2025-10, with the labels that each got.

#220 Enhanced Interview Experience Form with Structured Sections and Customizable Tags
  .gitignore
  backend/server.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/BrowseExperiences.jsx
  frontend/src/components/ExperienceCard.jsx
  frontend/src/components/ExperienceDetails.jsx
  frontend/src/components/InterviewExperience.jsx
  frontend/src/components/InterviewForm.jsx
  frontend/src/context/ExperienceContext.jsx
  frontend/src/context/index.js
  frontend/src/main.jsx
  package-lock.json
  package.json
Labels: gssoc25, Level 3

#247 adding interview experience
  backend/controllers/interviewExperienceController.js
  backend/models/InterviewExperience.js
  frontend/api/interviews.js
  frontend/src/components/InterviewForm.jsx
  frontend/src/context/ExperienceContext.jsx
Labels: gssoc25, Level 2

#260 UI Fix: Center section titles and add vertical padding to Admin Login page
  frontend/src/components/AdminLogin.css
  frontend/src/components/AdminLogin.jsx
  frontend/src/components/home.css
  frontend/src/components/home.jsx
Labels: level 1

#265 Password validations
  frontend/src/components/Sign.jsx
  frontend/src/components/sign.css
Labels: gssoc25, Level 2

#263 Added validations to interview form
  backend/models/InterviewExperience.js
  frontend/src/components/InterviewForm.jsx
  frontend/src/index.css
Labels: gssoc25, Level 2

#268 Updated Style of interview-experience-component
  frontend/src/components/InterviewExperience.jsx
Labels: gssoc25, Level 2

#264 Implemented search for interview experiences
  frontend/src/components/BrowseExperiences.jsx
Labels: gssoc25, Level 2

#273 added vercel.json file to resolve 404 error in redirecting while clicking register now button
  frontend/vercel.json
Labels: level 1, gssoc25

#274 Added pagination for interview experiences
  frontend/src/components/BrowseExperiences.jsx
  frontend/src/components/ExperienceCard.jsx
  frontend/src/components/ExperienceDetails.jsx
Labels: gssoc25, Level 2

#277 backtotopbutton added
  frontend/src/App.jsx
  frontend/src/components/Backtotopbutton.css
  frontend/src/components/Backtotopbutton.jsx
Labels: gssoc25, Level 2
