Repository Mohitjadaun2026/PMS-CGC-U, pull requests merged in 2025-08, with the labels that each got.

#67 Fixed: removed default Hover underline and color of contact us, correct contact phone icon #66
  frontend/src/components/Footer.jsx
  frontend/src/components/footer.css
Labels: level 1

#80 Redesigned Student dashboard
  frontend/src/components/StudentProfile.jsx
  frontend/src/components/studentProfile.css
Labels: Level 2

#79 feat: Add Custom JS Form Validation for Regsiter form
  frontend/src/components/Sign.jsx
  frontend/src/components/sign.css
Labels: gssoc25, Level 2

#89 Missing Hover Interaction on Section Elements #87
  frontend/src/components/home.css
Labels: level 1, gssoc25

#94 Fix: Page Scroll Position on Navigation
  frontend/src/App.jsx
  frontend/src/components/ScrollToTop.jsx
Labels: gssoc25, Level 2

#115 Added working social links in footer
  frontend/src/components/Footer.jsx
Labels: level 1, gssoc25

#118 Add contact form with validation and toast notifications
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Contact.jsx
  frontend/src/components/contact.css
Labels: gssoc25, Level 3

#120 issue create automate message added
  .github/workflows/issue-create-automate-message.yml
Labels: level 1, gssoc25
